#nome da pipeline
name: Testes Pipelines

# em que momento sera executada
on:
  pull_request:
    branches:
      - master

jobs:
  
  cypress-run:
    
    runs-on: ubuntu-latest
    
    
    steps:
      
      - name: Checkout repository/Clone do projeto
        uses: actions/checkout@v3
        
        
      - name: Run Testes
        run: npm install
        
     
      - name: Run Testes
        uses: cypress-io/github-action@v5
        with: 
          record: true
          env:
            CYPRESS_RECORD_KEY:${{ secrets.CYPRESS_RECORD_KEY }}
            
